name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with bandit
        run: bandit -r .
      - name: Unit tests with pytest
        run: coverage run --source=src/ -m pytest
      - name: Code test coverage with coverage
        run: coverage report -m

  image-build:
    needs:
      - test
    name: Image build
    uses: hajle-silesia/.github/.github/workflows/shared-image-build.yaml@v2.4.1
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}

  chart-update:
    needs:
      - image-build
    name: Chart update
    uses: hajle-silesia/.github/.github/workflows/shared-chart-update.yaml@v2.4.1
    with:
      docker-hub-image-repository-name: ${{ needs.build.outputs.docker-hub-repository-name }}
      image-tag: ${{ needs.build.outputs.tag }}
    secrets:
      github-token: ${{ secrets.PUSH_TOKEN }}